apiVersion: batch/v1
kind: Job
metadata:
  generateName: mp12-premium
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: mp12-premium
        image: bhtan888/mp12_docker:mp12_bt_docker
        env:
        - name: DATASET
          value: "kmnist"
        - name: TYPE
          value: "cnn"
        resources:
          limits:
            cpu: "900m"
        # command: ["python3", "classify.py"]
      restartPolicy: Never
  backoffLimit: 4